# Generated by Django 3.0.8 on 2020-07-14 15:56

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propic',
            name='propic',
            field=models.ImageField(upload_to='pro-pics/'),
        ),
        migrations.AlterField(
            model_name='subjectmodel',
            name='subject',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('ENG', 'English'), ('MATHS', 'Maths'), ('PHY', 'Physics'), ('BIO', 'Biology'), ('CHEM', 'Chemistry')], max_length=15),
        ),
    ]
