# Generated by Django 3.0.8 on 2020-07-14 19:48

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0002_auto_20200714_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectmodel',
            name='subject',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('ENG', 'English'), ('MATHS', 'Maths'), ('PHY', 'Physics'), ('BIO', 'Biology'), ('CHEM', 'Chemistry')], max_length=25),
        ),
    ]
