# Generated by Django 3.0.8 on 2020-07-14 21:38

import directory.models
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0003_auto_20200714_2348'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImporterModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.FileField(upload_to='csvfiles/', validators=[directory.models.validate_file_extension])),
            ],
            options={
                'db_table': 'ImporterFiles',
            },
        ),
        migrations.AlterField(
            model_name='subjectmodel',
            name='subject',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Computer Science', 'Computer Science'), ('Physics', 'Physics'), ('Mathematics', 'Mathematics'), ('History', 'History'), ('Geography', 'Geography'), ('Biology', 'Biology'), ('Chemistry', 'Chemistry'), ('English', 'English'), ('Arabic', 'Arabic')], max_length=75),
        ),
    ]
